{% set name = "quadax" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quadax-{{ version }}.tar.gz
  sha256: 842f95315f6f444f34713596d6e158f21cc54dc25b1ea1e1231821ff21f27723

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=40.8.0
    - wheel
    - versioneer-518
    - versioneer
    - pip
  run:
    - python >=3.8
    - equinox
    - jax >=0.3.2,<=0.5.0
    - numpy >=1.20.0,<2.0

test:
  imports:
    - quadax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/f0uriest/quadax
  summary: Numerical quadrature with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
