{% set name = "quadax" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quadax-{{ version }}.tar.gz
  sha256: c0cb80b3abb26b6b7cda5e30ceb6f1e8fd3c1a82ef21ecbcbd903cc58d6821e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=40.8.0
    - wheel
    - versioneer-518
    - versioneer
    - pip
  run:
    - python >=3.8
    - equinox
    - jax >=0.3.2,<=0.5.0
    - numpy >=1.20.0,<2.0

test:
  imports:
    - quadax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/f0uriest/quadax
  summary: Numerical quadrature with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
