{% set name = "quadax" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/f0uriest/quadax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 006dc011f396017264736e768e6d30fd5009d3ee4e4a1b82f48c343d76e9ae5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - equinox >=0.11.0,<=0.11.12
    - jax >=0.3.2,<=0.5.3
    - numpy >=1.20.0,<=2.2.4

test:
  imports:
    - quadax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/quadax
  summary: Numerical quadrature with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
