{% set name = "quadax" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/f0uriest/quadax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 62ad201e0e2638bf45aae50f001809c5ebcd206352e11994602f0f12f2795f04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - equinox >=0.11.0,<0.12
    - jax >=0.3.2,<0.6.0
    - numpy >=1.20.0,<3.0

test:
  imports:
    - quadax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/quadax
  summary: Numerical quadrature with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
