{% set name = "quadax" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quadax-{{ version }}.tar.gz
  sha256: 26b57477ea869fba8040ffbb6d9f67be3f63850856d0c5fb2e755676b640007b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - versioneer-518
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - equinox
    - jax >=0.3.2,<=0.5.0
    - numpy >=1.20.0,<2.0

test:
  imports:
    - quadax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/quadax
  summary: Numerical quadrature with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
