{% set name = "quadax" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/f0uriest/quadax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 17a51fe54e7c7a2170dd3fb61c98d1c76efbe55c879319c822f90efaf58be66a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - equinox >=0.11.0,<0.14
    - jax >=0.5.0,<0.12
    - numpy >=1.25.0,<2.6

test:
  imports:
    - quadax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/quadax
  summary: Numerical quadrature with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
