{% set name = "quadax" %}
{% set version = "0.2.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/f0uriest/quadax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b68e836e20f4473edcd4584a23348c51a6ede0575086c168aa257f19fd0b98e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - equinox >=0.11.0,<0.13
    - jax >=0.4.36,<0.7
    - numpy >=1.20.0,<2.3

test:
  imports:
    - quadax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/quadax
  summary: Numerical quadrature with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
